config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'
  get 'parking', to: 'welcome#parking'
  get 'contact', to: 'welcome#contact'

  resources :email

  namespace :admin do

    resources :emails

  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'welcome#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/email.rb
# frozen_string_literal: true

class Email < ApplicationRecord

  validates :sender_name, absence: true, length: { maximum: 100 }
  validates :sender_email, length: { maximum: 100 }, format: { with: /[a-zA-Z0-9_-]+/, message: 'only allows valid email'}
  validates :title, absence: true, length: { maximum: 100 }
  validates :content, absence: true, length: { maximum: 1000 }


  before_create { self.send_time = Time.now }


end

app/controllers/admin/application_controller.rb
class Admin::ApplicationController < ApplicationController

    http_basic_authenticate_with name: "admin", password: "admin"

    def authenticate_user
      render_404 unless current_user.admin?
    end

end

app/controllers/admin/emails_controller.rb
class Admin::EmailsController < Admin::ApplicationController

    def index
      @emails = Email.all
    end

    def show
      @email = Email.find(params[:id])
    end

    def destroy
      @email = Email.find(params[:id])
      @email.destroy
      redirect_to admin_email_path
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/emails_controller.rb
class EmailsController < ApplicationController

  def create
    @email = Email.new(email_params)
    if @email.save
      redirect_to @email
    else
      render action: "contact"
    end
  end


  private
    def email_params
      params.require(:email).permit(:sender_name, :sender_email, :title, :content)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index

  end

  def parking

  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/emails_helper.rb
module EmailsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/admin/email.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Ruby on Rails</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width">
</head>

<body>
<div class="container">

  <p>
    <strong>Sender_name:</strong>
    <%= @email.sender_name %>
  </p>

  <p>
    <strong>Sender_email:</strong>
    <%= @email.sender_email %>
  </p>

  <p>
    <strong>Title:</strong>
    <%= @email.title %>
  </p>

  <p>
    <strong>Content:</strong>
    <%= @email.content %>
  </p>
</div>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PracticeSystem</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/welcome/contact.html.erb
<!DOCTYPE html>
<html>
<body>
  <h1>If you have any questions or Suggestions, please send them to me from the email below.</h1>

  <%= form_with scope: :email, url: email_index_path, local: true do |form| %>

    <%# if @email.errors.any? %>
<!--      <div id="error_explanation">-->
<!--        <h2>-->
<!--          <%#= pluralize(@email.errors.count, "error") %> prohibited-->
<!--          this email from being saved:-->
<!--        </h2>-->
<!--        <ul>-->
          <%# @email.errors.full_messages.each do |msg| %>
<!--            <li><%#= msg %></li>-->
          <%# end %>
<!--        </ul>-->
<!--      </div>-->
    <%# end %>

    <p>
      <%= form.label :sender_name %><br>
      <%= form.text_field :sender_name %>
    </p>

    <p>
      <%= form.label :sender_email %><br>
      <%= form.text_field :sender_email %>
    </p>

    <p>
      <%= form.label :title %><br>
      <%= form.text_field :title %>
    </p>

    <p>
      <%= form.label :content %><br>
      <%= form.text_field :content %>
    </p>

    <p>
      <%= form.submit %>
    </p>
  <% end %>
</body>
</html>

app/views/welcome/email.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Ruby on Rails</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width">
</head>

<body>
<div class="container">

  <%= form_with scope: :emails, url: email_path, local: true do |form| %>
    <p>
      <%= form.label :title %><br>
      <%= form.text_field :title %>
    </p>

    <p>
      <%= form.label :text %><br>
      <%= form.text_area :text %>
    </p>

    <p>
      <%= form.submit %>
    </p>
  <% end %>
</div>
</body>
</html>

app/views/welcome/index.html.erb
<!DOCTYPE html>
<html>
<body>
  <h1>this is a  ...</h1>
</body>
</html>

app/views/welcome/parking.html.erb
<h1>dasdadadsa</h1>